### ISSUE TITLE
Do you have CrossEncoding model released on Huggingface? 

### ISSUE THREAD

**Issue by lijianw2** [ncbi/MedCPT#2]
Hi team, I see that you have released query encoder and document encoder on Huggingface. Is there any chance that you could release CrossEncoding model on Huggingface as well? Thanks!

**Comment by drqiaojin** [comment]
hi @lijianw2, thanks for your interest in our work. We will release the cross encoder as soon as possible. We will keep you posted.

**Comment by jw-sohn** [comment]
Hi guys,

Any updates on the release of the CrossEncoding model on Hugging Face? Looking forward to trying it out.

Thank you!

**Comment by uahmad235** [comment]
Hi  @Andy-jqa 

Could you share update on cross-encoder weights? Looking forward to trying them out.

Thank you for this commendable work.

**Comment by drqiaojin** [comment]
Hi @uahmad235 @lijianw2 @ahwatnow, sorry for the delay. 

We have uploaded the MedCPT CrossEncoder at: https://huggingface.co/ncbi/MedCPT-Cross-Encoder. You might want to use it to re-rank the articles returned by the MedCPT retriever. 

Please let me know if you have any questions.

Best,
Qiao
