### ISSUE TITLE
Inquiry on Document Retrieval Process Post MIPS

### ISSUE THREAD

**Issue by jw-sohn** [ncbi/MedCPT#3]
Hi @Andy-jqa 

I'm curious about the actual document retrieval process following the MIPS using FAISS. I could only find evaluation code of BEIR.

Could you please share any sample code for this?
Or did you use index returned from FAISS MIPS to retrieve documents from https://ftp.ncbi.nlm.nih.gov/pub/lu/MedCPT/pubmed_embeddings/?

Thanks!

**Comment by drqiaojin** [comment]
> Hi @Andy-jqa
> 
> I'm curious about the actual document retrieval process following the MIPS using FAISS. I could only find evaluation code of BEIR.
> 
> Could you please share any sample code for this? Or did you use index returned from FAISS MIPS to retrieve documents from https://ftp.ncbi.nlm.nih.gov/pub/lu/MedCPT/pubmed_embeddings/?
> 
> Thanks!

Sorry for the late reply. I am just wondering if this is still needed. If so, I can provide you with a sample code. @ahwatnow 

Thanks,
Qiao

**Comment by jw-sohn** [comment]
@Andy-jqa 

A sample code would be a big help! Thank you so much!

I also have a couple of questions regarding the handling of queries and articles with token lengths exceeding the default setting specified for the bi-encoder and cross-encoder:

1) Default token max_length for query encoder is set to 64. Are all of the queries in the training dataset shorter or equal to 64?
2) Default token max_length for article encoder and cross encoder is 512. While most PubMed abstracts fit within the 512 limit, not all do. If abstracts are combined with queries for reranking, more would be longer than 512. I am curious about how you addressed these issues.

Thank you again,
Jiwoong

**Comment by drqiaojin** [comment]
> @Andy-jqa
> 
> A sample code would be a big help! Thank you so much!
> 
> I also have a couple of questions regarding the handling of queries and articles with token lengths exceeding the default setting specified for the bi-encoder and cross-encoder:
> 
> 1. Default token max_length for query encoder is set to 64. Are all of the queries in the training dataset shorter or equal to 64?
> 2. Default token max_length for article encoder and cross encoder is 512. While most PubMed abstracts fit within the 512 limit, not all do. If abstracts are combined with queries for reranking, more would be longer than 512. I am curious about how you addressed these issues.
> 
> Thank you again, Jiwoong

Thanks, Jiwoong. @ahwatnow  For the example code with Faiss, please see here: https://github.com/ncbi/MedCPT/tree/main?tab=readme-ov-file#searching-pubmed-with-medcpt.

For your two questions,
1. Almost all queries in the training set are very short (< 10 tokens). Queries > 64 tokens are very uncommon. 
2. We simply truncate all title abstracts to 512 tokens. It works for most of the cases. Even in some cases the abstract is longer, it is likely we still don't miss key information since they might be reflected in the title.

Best,
Qiao

**Comment by jw-sohn** [comment]
Thank you so much!! Your research has been a big help for both me and my teammates in our project!!
