### ISSUE TITLE
Inquiry for reranking model

### ISSUE THREAD

**Issue by bishboi** [ncbi/MedCPT#4]
Hi! I was trying to figure out which model is to be used for reranking mentioned in the paper

I found out reranker/models.py has a function named Cross Encoder so i figured it out, can it be clearly mentioned in the repo readme and huggingface model description as well.

**Comment by drqiaojin** [comment]
@bishboi Thanks for your comment. Please use this for the pre-trained re-ranker: https://huggingface.co/ncbi/MedCPT-Cross-Encoder. There are code examples.
