### ISSUE TITLE
Two pmids chunks are equal

### ISSUE THREAD

**Issue by andreagregori** [ncbi/MedCPT#5]
On [link](https://ftp.ncbi.nlm.nih.gov/pub/lu/MedCPT/pubmed_embeddings/) two prides_chunk files contains the same content, in detail:
pmids_chunk_36.json  and pmids_chunk_37.json are equal.

Thanks and goodbye!

**Comment by drqiaojin** [comment]
@andreagregori Thank you very much for the reminder. We are working on it and will keep you informed.

**Comment by dimagalat** [comment]
Hey @Andy-jqa, any updates on this one?

**Comment by drqiaojin** [comment]
Fixed.
